apiVersion: apps/v1
kind: Deployment
metadata:
  name: blacklist-deployment
  labels:
    app: blacklist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blacklist
  template:
    metadata:
      labels:
        app: blacklist
    spec:
      containers:
        - name: blacklist
          image: yoramnagdocker/black-list-service:0.0.9-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: creditcard-configmap
                  key: BLACK_LIST_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: creditcard-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: creditcard-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: creditcard-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: blacklist
spec:
  selector:
    app: blacklist
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080